# Generated by Django 5.2 on 2025-06-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adresse',
        ),
    ]
