# Generated by Django 5.2 on 2025-06-13 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='adresse_livraison',
        ),
    ]
