# Generated by Django 5.2 on 2025-06-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_remove_commande_adresse_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('RECUPEREE', 'Récupérée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='commandes.commande')),
            ],
        ),
    ]
