# Generated by Django 5.2 on 2025-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_commande_statut_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='est_gestionnaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
