# Generated by Django 5.2 on 2025-06-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categorie',
            field=models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat'), ('dessert', 'Dessert'), ('boisson', 'Boisson')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
