# Generated by Django 5.2 on 2025-06-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menu_categorie_delete_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categorie',
            field=models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat'), ('dessert', 'Dessert'), ('boisson', 'Boisson'), ('fast-food', 'Fast-Food'), ('snack', 'Snack')], max_length=20),
        ),
    ]
